//Main Cateogary

export const ADD_MAINCATEOGARY="ADD_MAINCATEOGARY"
export const  ADD_MAINCATEOGARY_RED="ADD_MAINCATEOGARY_RED"
export const GET_MAINCATEOGARY="GET_MAINCATEOGARY"
export const  GET_MAINCATEOGARY_RED="GET_MAINCATEOGARY_RED"
export const UPDATE_MAINCATEOGARY="UPDATE_MAINCATEOGARY"
export const  UPDATE_MAINCATEOGARY_RED="UPDATE_MAINCATEOGARY_RED"
export const DELETE_MAINCATEOGARY="DELETE_MAINCATEOGARY"
export const  DELETE_MAINCATEOGARY_RED="DELETE_MAINCATEOGARY_RED"

//Sub Cateogary
export const ADD_SUBCATEOGARY="ADD_SUBCATEOGARY"
export const  ADD_SUBCATEOGARY_RED="ADD_SUBCATEOGARY_RED"
export const GET_SUBCATEOGARY="GET_SUBCATEOGARY"
export const  GET_SUBCATEOGARY_RED="GET_SUBCATEOGARY_RED"
export const UPDATE_SUBCATEOGARY="UPDATE_SUBCATEOGARY"
export const  UPDATE_SUBCATEOGARY_RED="UPDATE_SUBCATEOGARY_RED"
export const DELETE_SUBCATEOGARY="DELETE_SUBCATEOGARY"
export const  DELETE_SUBCATEOGARY_RED="DELETE_SUBCATEOGARY_RED"

//Brand
export const ADD_BRAND="ADD_BRAND"
export const  ADD_BRAND_RED="ADD_BRAND_RED"
export const GET_BRAND="GET_BRAND"
export const  GET_BRAND_RED="GET_BRAND_RED"
export const UPDATE_BRAND="UPDATE_BRAND"
export const  UPDATE_BRAND_RED="UPDATE_BRAND_RED"
export const DELETE_BRAND="DELETE_BRAND"
export const  DELETE_BRAND_RED="DELETE_BRAND_RED"

//Product
export const ADD_PRODUCT="ADD_PRODUCT"
export const  ADD_PRODUCT_RED="ADD_PRODUCT_RED"
export const GET_PRODUCT="GET_PRODUCT"
export const  GET_PRODUCT_RED="GET_PRODUCT_RED"
export const UPDATE_PRODUCT="UPDATE_PRODUCT"
export const  UPDATE_PRODUCT_RED="UPDATE_PRODUCT_RED"
export const DELETE_PRODUCT="DELETE_PRODUCT"
export const  DELETE_PRODUCT_RED="DELETE_PRODUCT_RED"


